// Fuente única de contenido de ejemplo. La importa prisma/seed.ts.
import type { Prisma } from "@prisma/client";

type SampleProduct = {
  name: string;
  slug: string;
  description: string;
  price: number;
  stock: number;
  category: string;
  linea?: string;
  featured: boolean;
  images: string[];
  specs: Prisma.InputJsonValue;
  rating: number;
  reviewCount: number;
};

type SampleRecipe = {
  name: string;
  slug: string;
  emoji: string;
  description: string;
  category: string;
  difficulty: string;
  time: string;
  temperature: string;
  ingredients: string[];
  equipment: string[];
  steps: string[];
  variations: string[];
  uses: string[];
  image: string;
  images: string[];
  featured: boolean;
  season: string | null;
};

const FOOD_SPECS = (peso: string) => ({
  peso,
  conservación: "Lugar fresco y seco",
  "vida útil": "6 meses",
});

export const SAMPLE_PRODUCTS: SampleProduct[] = [
  {
    name: "Charqui Clásico 100g",
    slug: "charqui-clasico-100g",
    description:
      "Carne de res deshidratada al estilo norteño, salada en su punto justo. Alta en proteínas, sin conservantes.",
    price: 4200,
    stock: 40,
    category: "Charqui",
    featured: true,
    images: [],
    specs: FOOD_SPECS("100g"),
    rating: 4.8,
    reviewCount: 24,
  },
  {
    name: "Charqui Picante 100g",
    slug: "charqui-picante-100g",
    description:
      "Nuestro charqui con un toque de ají molido. Para los que buscan intensidad.",
    price: 4500,
    stock: 25,
    category: "Charqui",
    featured: true,
    images: [],
    specs: FOOD_SPECS("100g"),
    rating: 4.6,
    reviewCount: 18,
  },
  {
    name: "Mix de Frutas Deshidratadas 200g",
    slug: "mix-frutas-deshidratadas-200g",
    description:
      "Manzana, pera, ananá y banana deshidratadas. Dulzor natural, ideal para la mochila.",
    price: 3800,
    stock: 60,
    category: "Frutas",
    featured: true,
    images: [],
    specs: FOOD_SPECS("200g"),
    rating: 4.9,
    reviewCount: 31,
  },
  {
    name: "Manzana Deshidratada 150g",
    slug: "manzana-deshidratada-150g",
    description: "Rodajas finas de manzana, crujientes y sin azúcar agregada.",
    price: 2900,
    stock: 50,
    category: "Frutas",
    featured: false,
    images: [],
    specs: FOOD_SPECS("150g"),
    rating: 4.5,
    reviewCount: 12,
  },
  {
    name: "Tomate Deshidratado 100g",
    slug: "tomate-deshidratado-100g",
    description:
      "Tomate en aceite de oliva listo para tus pastas, ensaladas y picadas.",
    price: 3500,
    stock: 30,
    category: "Verduras",
    featured: false,
    images: [],
    specs: FOOD_SPECS("100g"),
    rating: 4.4,
    reviewCount: 9,
  },
  {
    name: "Snack Mix Energía 180g",
    slug: "snack-mix-energia-180g",
    description:
      "Frutas deshidratadas, semillas y trozos de charqui. El snack completo para entrenar.",
    price: 5100,
    stock: 35,
    category: "Snacks",
    featured: true,
    images: [],
    specs: FOOD_SPECS("180g"),
    rating: 4.7,
    reviewCount: 27,
  },
  {
    name: "Banana Chips 150g",
    slug: "banana-chips-150g",
    description: "Banana deshidratada crocante, energía pura para el día.",
    price: 2700,
    stock: 0,
    category: "Snacks",
    featured: false,
    images: [],
    specs: FOOD_SPECS("150g"),
    rating: 4.3,
    reviewCount: 14,
  },

  // --- Equipos deshidratadores: Línea Familiar ---
  {
    name: "Deshidratador Familiar BO-3",
    slug: "deshidratador-familiar-bo-3",
    description:
      "Deshidratador compacto de 3 bandejas, ideal para empezar en casa. Bajo consumo y fácil de usar.",
    price: 119000,
    stock: 15,
    category: "Deshidratadores",
    linea: "Familiar",
    featured: false,
    images: [],
    specs: {
      bandejas: "3",
      potencia: "350W",
      temperatura: "35°C a 68°C",
      garantía: "1 año",
    },
    rating: 4.6,
    reviewCount: 11,
  },
  {
    name: "Deshidratador Hogareño BO-6",
    slug: "deshidratador-hogareno-bo-6",
    description:
      "Deshidratador de 6 bandejas con control de temperatura. Hacé tus propios alimentos en casa.",
    price: 189000,
    stock: 8,
    category: "Deshidratadores",
    linea: "Familiar",
    featured: false,
    images: [],
    specs: {
      bandejas: "6",
      potencia: "500W",
      temperatura: "35°C a 70°C",
      garantía: "1 año",
    },
    rating: 5,
    reviewCount: 5,
  },
  {
    name: "Deshidratador Familiar BO-9",
    slug: "deshidratador-familiar-bo-9",
    description:
      "Deshidratador de 9 bandejas para familias grandes o producción casera intensiva.",
    price: 279000,
    stock: 10,
    category: "Deshidratadores",
    linea: "Familiar",
    featured: false,
    images: [],
    specs: {
      bandejas: "9",
      potencia: "650W",
      temperatura: "35°C a 70°C",
      garantía: "2 años",
    },
    rating: 4.8,
    reviewCount: 8,
  },

  // --- Equipos deshidratadores: Línea Comercial ---
  {
    name: "Deshidratador Comercial BO-16",
    slug: "deshidratador-comercial-bo-16",
    description:
      "Equipo de 16 bandejas en acero inoxidable para emprendimientos y pequeños comercios.",
    price: 690000,
    stock: 6,
    category: "Deshidratadores",
    linea: "Comercial",
    featured: false,
    images: [],
    specs: {
      bandejas: "16",
      potencia: "1200W",
      temperatura: "35°C a 75°C",
      garantía: "2 años",
      construcción: "Acero inoxidable",
    },
    rating: 4.9,
    reviewCount: 6,
  },
  {
    name: "Deshidratador Comercial BO-30",
    slug: "deshidratador-comercial-bo-30",
    description:
      "Equipo de 30 bandejas en acero inoxidable para producción comercial sostenida.",
    price: 1290000,
    stock: 3,
    category: "Deshidratadores",
    linea: "Comercial",
    featured: false,
    images: [],
    specs: {
      bandejas: "30",
      potencia: "2200W",
      temperatura: "35°C a 80°C",
      garantía: "2 años",
      construcción: "Acero inoxidable",
    },
    rating: 5,
    reviewCount: 4,
  },
  {
    name: "Deshidratador Comercial BO-48 Industrial",
    slug: "deshidratador-comercial-bo-48",
    description:
      "Equipo industrial de 48 bandejas en acero inoxidable para alta producción continua.",
    price: 2450000,
    stock: 2,
    category: "Deshidratadores",
    linea: "Comercial",
    featured: false,
    images: [],
    specs: {
      bandejas: "48",
      potencia: "3500W",
      temperatura: "35°C a 80°C",
      garantía: "3 años",
      construcción: "Acero inoxidable",
    },
    rating: 5,
    reviewCount: 2,
  },
];

export const SAMPLE_RECIPES: SampleRecipe[] = [
  // ─── BÁSICO ──────────────────────────────────────────────────────────────
  {
    name: "Chips de Manzana",
    slug: "chips-de-manzana",
    emoji: "🍎",
    description:
      "Rodajas crujientes de manzana deshidratada, perfectas como snack saludable o para decorar porridge y ensaladas.",
    category: "Básico",
    difficulty: "Fácil",
    time: "6-8 horas",
    temperature: "55°C",
    ingredients: [
      "4 manzanas medianas (variedad a elección)",
      "Jugo de 1 limón",
      "1 cucharadita de canela en polvo (opcional)",
    ],
    equipment: [
      "Deshidratador Bio Origen con bandejas",
      "Mandolina o cuchillo afilado",
      "Bol con agua y limón",
    ],
    steps: [
      "Lavar bien las manzanas y cortarlas en rodajas de 3-4 mm de espesor.",
      "Sumergir las rodajas en agua con jugo de limón por 5 minutos para evitar la oxidación.",
      "Escurrir y secar con papel absorbente.",
      "Espolvorear canela si se desea.",
      "Distribuir en bandejas del Deshidratador Bio Origen sin superponer.",
      "Deshidratar a 55°C durante 6-8 horas hasta que estén crujientes.",
      "Dejar enfriar completamente antes de guardar en frasco hermético.",
    ],
    variations: [
      "Con ralladura de naranja y cardamomo",
      "Con una pizca de sal y pimienta de Cayena para versión salada",
    ],
    uses: ["Snack directo", "Decoración de tortas y porridge", "Granola casera"],
    image: "/recetas/chips-de-manzana.jpg",
    images: [],
    featured: true,
    season: "Otoño",
  },
  {
    name: "Plátanos Deshidratados",
    slug: "platanos-deshidratados",
    emoji: "🍌",
    description:
      "Rodajas de banana deshidratada, naturalmente dulces y energéticas. Ideales para el desayuno o el bolso.",
    category: "Básico",
    difficulty: "Fácil",
    time: "8-10 horas",
    temperature: "57°C",
    ingredients: ["6 bananas maduras pero firmes", "Jugo de 1 limón"],
    equipment: ["Deshidratador Bio Origen", "Cuchillo y tabla"],
    steps: [
      "Pelar las bananas y cortarlas en rodajas de 5 mm.",
      "Rociar con jugo de limón para retardar la oxidación.",
      "Colocar en bandejas sin superponer.",
      "Deshidratar a 57°C por 8-10 horas, dando vuelta a mitad de proceso.",
      "Están listas cuando estén secas pero levemente flexibles.",
    ],
    variations: [
      "Bañadas en chocolate oscuro derretido",
      "Con miel y semillas de chía antes de deshidratar",
    ],
    uses: ["Snack energético", "Mix de frutos secos", "Cereales y muesli"],
    image: "/recetas/platanos-deshidratados.jpg",
    images: [],
    featured: false,
    season: null,
  },
  {
    name: "Fresas Deshidratadas",
    slug: "fresas-deshidratadas",
    emoji: "🍓",
    description:
      "Fresas liofilizadas de forma artesanal: concentran todo el sabor y se vuelven ligeramente crujientes.",
    category: "Básico",
    difficulty: "Fácil",
    time: "8-12 horas",
    temperature: "60°C",
    ingredients: ["500 g de fresas frescas maduras"],
    equipment: ["Deshidratador Bio Origen", "Cuchillo y tabla"],
    steps: [
      "Lavar y secar bien las fresas.",
      "Retirar los cabos y cortar en mitades o rodajas de 5 mm.",
      "Colocar con el lado cortado hacia arriba en las bandejas.",
      "Deshidratar a 60°C por 8-12 horas según el grosor.",
      "Dejar enfriar; deben quedar crocantes o levemente masticables según preferencia.",
    ],
    variations: [
      "Enteras (tiempo mayor: 14-16 horas)",
      "Con vainilla: remojar 30 min en jugo de naranja con extracto de vainilla antes de deshidratar",
    ],
    uses: ["Snack saludable", "Yogur y helados", "Decoración de postres"],
    image: "/recetas/fresas-deshidratadas.jpg",
    images: [],
    featured: false,
    season: "Primavera",
  },
  {
    name: "Chips de Zanahoria",
    slug: "chips-de-zanahoria",
    emoji: "🥕",
    description:
      "Chips crocantes de zanahoria, ligeramente condimentadas. Un snack vegetal lleno de betacarotenos.",
    category: "Básico",
    difficulty: "Fácil",
    time: "6-8 horas",
    temperature: "57°C",
    ingredients: [
      "500 g de zanahorias peladas",
      "1 cucharada de aceite de oliva",
      "Sal marina y pimienta a gusto",
    ],
    equipment: ["Deshidratador Bio Origen", "Mandolina o cuchillo", "Bol para mezclar"],
    steps: [
      "Pelar las zanahorias y cortarlas en rodajas finas de 2-3 mm.",
      "Mezclar con aceite, sal y pimienta en un bol.",
      "Distribuir en bandejas del Deshidratador Bio Origen.",
      "Deshidratar a 57°C durante 6-8 horas hasta que estén crujientes.",
    ],
    variations: [
      "Con comino y pimentón ahumado",
      "Con ajo en polvo y hierbas provenzales",
    ],
    uses: ["Snack salado", "Acompañamiento de sopas", "Dips y hummus"],
    image: "/recetas/chips-de-zanahoria.jpg",
    images: [],
    featured: false,
    season: null,
  },
  {
    name: "Hierbas Aromáticas",
    slug: "hierbas-aromaticas",
    emoji: "🌿",
    description:
      "Orégano, tomillo, romero y albahaca deshidratados en casa para conservar todo su aroma y sabor.",
    category: "Básico",
    difficulty: "Fácil",
    time: "4-6 horas",
    temperature: "35°C",
    ingredients: [
      "Manojo de orégano fresco",
      "Manojo de tomillo fresco",
      "Ramitas de romero",
      "Hojas de albahaca",
    ],
    equipment: ["Deshidratador Bio Origen", "Mallas de secado finas"],
    steps: [
      "Lavar suavemente las hierbas y secar con papel absorbente.",
      "Separar las hojas de los tallos gruesos.",
      "Extender en bandejas con malla fina para que no caigan.",
      "Deshidratar a 35°C durante 4-6 horas hasta que se desmigajen fácilmente.",
      "Guardar en frascos oscuros bien tapados.",
    ],
    variations: [
      "Mix de hierbas italianas (orégano, albahaca, tomillo)",
      "Mezcla de hierbas para asado (romero, orégano, ajo)",
    ],
    uses: ["Condimento en pizzas y pastas", "Infusiones", "Aceites aromatizados"],
    image: "/recetas/hierbas-aromaticas.jpg",
    images: [],
    featured: false,
    season: "Primavera",
  },

  {
    name: "Rodajas de Naranja Deshidratadas",
    slug: "rodajas-de-naranja-deshidratadas",
    emoji: "🍊",
    description:
      "Ruedas enteras de naranja secadas lentamente: conservan el color translúcido y el aroma cítrico. Ideales para infusiones, tragos y decoración.",
    category: "Básico",
    difficulty: "Fácil",
    time: "10-14 horas",
    temperature: "55°C",
    ingredients: [
      "4 naranjas de cáscara fina (preferentemente sin encerar)",
      "1 cucharada de bicarbonato (para lavar la cáscara)",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Cuchillo bien afilado o mandolina",
      "Papel absorbente",
    ],
    steps: [
      "Lavar las naranjas frotando la cáscara con agua y bicarbonato; enjuagar y secar.",
      "Cortar rodajas parejas de 4-5 mm sin pelar, descartando las puntas.",
      "Secar cada rodaja con papel absorbente para quitar el exceso de jugo.",
      "Distribuir en las bandejas del Deshidratador Bio Origen sin que se toquen entre sí.",
      "Deshidratar a 55°C durante 10-14 horas, girando las bandejas a mitad de proceso.",
      "Están listas cuando la pulpa queda translúcida y la cáscara se siente seca y rígida.",
      "Enfriar sobre una rejilla antes de guardar en frasco hermético.",
    ],
    variations: [
      "Con pomelo rosado o limón para una mezcla cítrica",
      "Espolvoreadas con canela o jengibre en polvo antes de secar",
    ],
    uses: [
      "Infusiones y aguas saborizadas",
      "Decoración de tragos y repostería",
      "Guirnaldas y decoración aromática",
    ],
    image: "/recetas/rodajas-de-naranja-deshidratadas.jpg",
    images: [],
    featured: true,
    season: "Invierno",
  },
  {
    name: "Ananá Deshidratado",
    slug: "anana-deshidratado",
    emoji: "🍍",
    description:
      "Aros de ananá secados hasta quedar tiernos y masticables, con un dulzor concentrado que no necesita azúcar agregada.",
    category: "Básico",
    difficulty: "Fácil",
    time: "12-16 horas",
    temperature: "57°C",
    ingredients: ["1 ananá maduro (aprox. 1,5 kg)", "Jugo de ½ limón (opcional)"],
    equipment: [
      "Deshidratador Bio Origen",
      "Cuchillo grande y tabla",
      "Descorazonador de ananá (opcional)",
    ],
    steps: [
      "Cortar las puntas del ananá y pelarlo retirando bien los 'ojos'.",
      "Cortar en rodajas de 6-8 mm y quitar el centro fibroso con un descorazonador o cuchillo.",
      "Escurrir las rodajas unos minutos sobre una rejilla; el ananá suelta mucho jugo.",
      "Rociar con limón si se busca realzar la acidez.",
      "Distribuir en las bandejas del Deshidratador Bio Origen sin superponer.",
      "Deshidratar a 57°C durante 12-16 horas, rotando las bandejas cada 4 horas.",
      "Retirar cuando estén flexibles y sin humedad al apretarlas; si se busca crocante, extender 3-4 horas más.",
    ],
    variations: [
      "En bastones finos, para snack tipo golosina",
      "Espolvoreado con coco rallado antes de deshidratar",
    ],
    uses: ["Snack dulce sin azúcar", "Mix de frutas deshidratadas", "Repostería y granolas"],
    image: "/recetas/anana-deshidratado.jpg",
    images: [],
    featured: false,
    season: "Verano",
  },
  {
    name: "Chips de Kale",
    slug: "chips-de-kale",
    emoji: "🥬",
    description:
      "Hojas de kale condimentadas y secadas a baja temperatura: quedan aireadas y crocantes, sin la amargura del horno.",
    category: "Básico",
    difficulty: "Fácil",
    time: "4-6 horas",
    temperature: "45°C",
    ingredients: [
      "1 atado grande de kale (col rizada)",
      "1 cucharada de aceite de oliva",
      "1 cucharada de levadura nutricional (opcional)",
      "Sal marina fina y pimienta",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Bol grande",
      "Centrifugadora de verduras o repasador limpio",
    ],
    steps: [
      "Lavar el kale y secarlo muy bien; la humedad remanente arruina la textura.",
      "Retirar el nervio central grueso y cortar las hojas en trozos de 5-6 cm.",
      "Masajear las hojas con el aceite hasta que queden apenas brillantes, sin exceso.",
      "Condimentar con sal, pimienta y levadura nutricional.",
      "Distribuir en las bandejas del Deshidratador Bio Origen bien separadas.",
      "Deshidratar a 45°C durante 4-6 horas hasta que se quiebren al tacto.",
      "Guardar apenas se enfríen: el kale reabsorbe humedad del ambiente muy rápido.",
    ],
    variations: [
      "Versión 'queso': agregar castañas de cajú molidas y pimentón",
      "Versión oriental: aceite de sésamo, semillas de sésamo y un toque de salsa de soja",
    ],
    uses: ["Snack liviano", "Topping de ensaladas y bowls", "Acompañamiento de dips"],
    image: "/recetas/chips-de-kale.jpg",
    images: [],
    featured: false,
    season: "Invierno",
  },

  // ─── INTERMEDIO ──────────────────────────────────────────────────────────
  {
    name: "Tomates Secos",
    slug: "tomates-secos",
    emoji: "🍅",
    description:
      "Tomates cherry o perita deshidratados con hierbas, concentrando un sabor intenso y dulce. Un clásico gourmet.",
    category: "Intermedio",
    difficulty: "Media",
    time: "10-14 horas",
    temperature: "60°C",
    ingredients: [
      "1 kg de tomates perita o cherry",
      "2 dientes de ajo en láminas",
      "Orégano seco a gusto",
      "Sal marina y pimienta",
      "Aceite de oliva (opcional, para conservar)",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Cuchillo y tabla",
      "Frasco de vidrio para conservar",
    ],
    steps: [
      "Lavar los tomates y cortarlos al medio (o en cuartos si son grandes).",
      "Retirar el exceso de semillas con una cuchara.",
      "Condimentar con sal, pimienta, ajo y orégano.",
      "Colocar con el lado cortado hacia arriba en bandejas.",
      "Deshidratar a 60°C por 10-14 horas; deben quedar blandos pero sin humedad.",
      "Guardar en frasco con aceite de oliva o en bolsa sellada al vacío.",
    ],
    variations: [
      "Con albahaca fresca y pimienta negra molida gruesa",
      "Con chile seco para versión picante",
    ],
    uses: ["Pizzas y focaccias", "Pastas y risottos", "Antipasto"],
    image: "/recetas/tomates-secos.jpg",
    images: [],
    featured: true,
    season: "Verano",
  },
  {
    name: "Chips Vegetales Mixtos",
    slug: "chips-vegetales-mixtos",
    emoji: "🥦",
    description:
      "Combinación colorida de remolacha, zucchini y papa andina deshidratadas con especias. Crujientes y saludables.",
    category: "Intermedio",
    difficulty: "Media",
    time: "7-10 horas",
    temperature: "57°C",
    ingredients: [
      "2 remolachas medianas",
      "2 zucchinis",
      "2 papas andinas medianas",
      "1 cucharada de aceite de oliva",
      "Sal, pimienta, pimentón a gusto",
    ],
    equipment: ["Deshidratador Bio Origen con varias bandejas", "Mandolina (recomendado)", "Bol para condimentar"],
    steps: [
      "Lavar y pelar los vegetales.",
      "Cortar en rodajas uniformes de 2-3 mm con mandolina.",
      "Mezclar cada vegetal por separado con aceite y condimentos.",
      "Distribuir en bandejas separadas (los tiempos varían por tipo).",
      "Deshidratar a 57°C: zucchini 6-7 hs, remolacha 8-9 hs, papa 9-10 hs.",
      "Retirar cada uno cuando estén crujientes.",
    ],
    variations: [
      "Agregar chips de batata y zanahoria para más variedad",
      "Versión picante con cayena y comino",
    ],
    uses: ["Snack colorido", "Guarnición de sopas", "Bowl toppings"],
    image: "/recetas/chips-vegetales-mixtos.jpg",
    images: [],
    featured: false,
    season: null,
  },
  {
    name: "Leather de Frutas",
    slug: "leather-de-frutas",
    emoji: "🍑",
    description:
      "Puré de frutas extendido y deshidratado hasta obtener una lámina flexible y naturalmente dulce.",
    category: "Intermedio",
    difficulty: "Media",
    time: "8-10 horas",
    temperature: "57°C",
    ingredients: [
      "500 g de frutos de estación (durazno, mango, fresa o mezcla)",
      "1 cucharada de miel o azúcar (opcional)",
      "Jugo de ½ limón",
    ],
    equipment: [
      "Deshidratador Bio Origen con lámina de silicona",
      "Licuadora o procesadora",
      "Espátula",
    ],
    steps: [
      "Lavar, pelar y descarozar las frutas.",
      "Procesar hasta obtener un puré liso.",
      "Agregar miel y limón; mezclar bien.",
      "Extender sobre la lámina de silicona con un grosor de 5-6 mm.",
      "Deshidratar a 57°C por 8-10 horas hasta que no quede pegajoso al tacto.",
      "Dejar enfriar y cortar en tiras; enrollar con papel film.",
    ],
    variations: [
      "Durazno con canela",
      "Mango con coco rallado encima antes de deshidratar",
    ],
    uses: ["Snack para niños", "Merienda", "Decoración de tortas"],
    image: "/recetas/leather-de-frutas.jpg",
    images: [],
    featured: false,
    season: "Verano",
  },
  {
    name: "Condimento Casero en Polvo",
    slug: "condimento-casero-en-polvo",
    emoji: "🧂",
    description:
      "Mezcla de vegetales y hierbas deshidratadas trituradas que da profundidad de sabor a cualquier plato.",
    category: "Intermedio",
    difficulty: "Media",
    time: "10-12 horas",
    temperature: "55°C",
    ingredients: [
      "2 cebollas medianas",
      "1 cabeza de ajo",
      "2 pimientos rojos",
      "2 zanahorias",
      "Hierbas frescas: perejil, apio, orégano",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Procesadora o molinillo de café",
      "Tamiz",
      "Frascos de vidrio",
    ],
    steps: [
      "Cortar todos los vegetales en rodajas finas.",
      "Deshidratar a 55°C por 10-12 horas hasta que estén completamente secos.",
      "Dejar enfriar completamente.",
      "Procesar o moler hasta obtener polvo fino.",
      "Tamizar para homogeneizar el tamaño.",
      "Guardar en frascos herméticos lejos de la luz.",
    ],
    variations: [
      "Condimento picante: agregar chile y pimienta negra",
      "Condimento mediterráneo: agregar tomate seco molido",
    ],
    uses: [
      "Sopas y guisos",
      "Sazonar carnes",
      "Reemplaza el caldo en polvo industrial",
    ],
    image: "/recetas/condimento-casero-en-polvo.jpg",
    images: [],
    featured: false,
    season: null,
  },

  {
    name: "Sopa Instantánea para Camping",
    slug: "sopa-instantanea-para-camping",
    emoji: "🍲",
    description:
      "Un frasco con verduras y legumbres deshidratadas listo para rehidratar con agua caliente. Pesa poco, dura meses y rinde una comida real en el cerro.",
    category: "Intermedio",
    difficulty: "Media",
    time: "10-12 horas",
    temperature: "55°C",
    ingredients: [
      "2 zanahorias en cubos chicos",
      "1 puerro y 1 cebolla en rodajas finas",
      "1 zapallo anco chico en cubos de 1 cm",
      "200 g de lentejas ya cocidas y escurridas",
      "1 taza de arvejas cocidas",
      "Perejil y apio picados",
      "Sal, pimienta y comino a gusto",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Olla para blanquear",
      "Bandeja con malla fina",
      "Frascos herméticos o bolsas con cierre",
    ],
    steps: [
      "Blanquear zanahoria, zapallo y puerro 2-3 minutos en agua hirviendo y cortar la cocción en agua con hielo.",
      "Escurrir muy bien y secar con repasador; el blanqueado acelera el secado y fija el color.",
      "Distribuir cada ingrediente en bandejas separadas: las legumbres cocidas van sobre malla fina.",
      "Deshidratar todo junto a 55°C durante 10-12 horas hasta que no quede nada de humedad.",
      "Comprobar el punto partiendo un cubo al medio: no debe verse húmedo en el centro.",
      "Dejar enfriar por completo y recién ahí mezclar todo con los condimentos.",
      "Envasar en porciones individuales de aproximadamente 60 g por ración.",
      "Para servir: cubrir con 350 ml de agua hirviendo, tapar y esperar 12-15 minutos.",
    ],
    variations: [
      "Con fideos de sémola finos agregados en seco al frasco",
      "Versión crema: sumar polvo de zapallo y leche en polvo al momento de envasar",
    ],
    uses: ["Trekking y camping", "Vianda de oficina", "Reserva de despensa"],
    image: "/recetas/sopa-instantanea-para-camping.jpg",
    images: [],
    featured: true,
    season: null,
  },
  {
    name: "Jengibre y Cúrcuma Deshidratados",
    slug: "jengibre-y-curcuma-deshidratados",
    emoji: "🫚",
    description:
      "Raíces cortadas finas y secadas a baja temperatura para conservar sus aceites esenciales. Se usan en láminas o molidas en polvo.",
    category: "Intermedio",
    difficulty: "Media",
    time: "6-10 horas",
    temperature: "50°C",
    ingredients: [
      "300 g de jengibre fresco",
      "200 g de cúrcuma fresca",
      "Jugo de 1 limón (opcional, para el jengibre)",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Mandolina o pelapapas",
      "Guantes descartables (la cúrcuma tiñe mucho)",
      "Molinillo de café o mortero",
    ],
    steps: [
      "Lavar bien las raíces con cepillo; si la piel está sana no hace falta pelarlas.",
      "Cortar láminas de 2 mm con mandolina, lo más parejas posible.",
      "Trabajar la cúrcuma con guantes y sobre una tabla que no se manche.",
      "Distribuir en bandejas separadas del Deshidratador Bio Origen, sin superponer.",
      "Deshidratar a 50°C durante 6-10 horas hasta que las láminas se quiebren en seco.",
      "Enfriar completamente antes de moler: en caliente el polvo se apelmaza.",
      "Moler en tandas cortas y tamizar; guardar en frasco oscuro y hermético.",
    ],
    variations: [
      "Láminas de jengibre azucaradas para infusión dulce",
      "Mezcla 'golden': cúrcuma, jengibre y pimienta negra molidos juntos",
    ],
    uses: [
      "Infusiones y golden milk",
      "Curries y guisos",
      "Reemplazo del jengibre en polvo comprado",
    ],
    image: "/recetas/jengibre-y-curcuma-deshidratados.jpg",
    images: [],
    featured: false,
    season: null,
  },
  {
    name: "Melts de Yogur y Fruta",
    slug: "melts-de-yogur-y-fruta",
    emoji: "🥛",
    description:
      "Botoncitos de yogur con puré de fruta que se deshacen en la boca. El snack favorito de los chicos, sin colorantes ni conservantes.",
    category: "Intermedio",
    difficulty: "Media",
    time: "8-12 horas",
    temperature: "52°C",
    ingredients: [
      "400 g de yogur natural entero (cuanto más firme, mejor)",
      "150 g de fruta madura (frutilla, mango o banana)",
      "1 cucharada de miel (opcional)",
    ],
    equipment: [
      "Deshidratador Bio Origen con lámina de silicona",
      "Licuadora o mixer",
      "Manga pastelera con boquilla lisa fina",
    ],
    steps: [
      "Escurrir el yogur 2 horas en un colador con lienzo para que pierda suero.",
      "Procesar la fruta hasta obtener un puré liso y colarlo si tiene semillas.",
      "Mezclar el yogur escurrido con el puré y la miel.",
      "Cargar la manga y formar botones de 1,5 cm sobre la lámina de silicona, separados entre sí.",
      "Deshidratar a 52°C durante 8-12 horas hasta que se despeguen solos y no queden pegajosos.",
      "Enfriar sobre la misma lámina antes de despegarlos.",
      "Guardar en frasco hermético en la heladera y consumir dentro de las 2 semanas.",
    ],
    variations: [
      "Con yogur griego para una textura más cremosa",
      "Bicolor: alternar botones de dos purés distintos",
    ],
    uses: ["Merienda infantil", "Topping de granola", "Snack para la mochila"],
    image: "/recetas/melts-de-yogur-y-fruta.jpg",
    images: [],
    featured: false,
    season: null,
  },

  // ─── AVANZADO ────────────────────────────────────────────────────────────
  {
    name: "Beef Jerky",
    slug: "beef-jerky",
    emoji: "🥩",
    description:
      "Carne de res marinada y deshidratada al estilo americano. Proteína concentrada con sabor intenso y ahumado.",
    category: "Avanzado",
    difficulty: "Difícil",
    time: "6-8 horas + 12 hs marinado",
    temperature: "70°C",
    ingredients: [
      "500 g de peceto o nalga sin grasa, en tiras de 5 mm",
      "60 ml de salsa de soja",
      "2 cucharadas de salsa Worcestershire",
      "1 cucharadita de ajo en polvo",
      "1 cucharadita de cebolla en polvo",
      "½ cucharadita de pimienta negra",
      "½ cucharadita de pimentón ahumado",
    ],
    equipment: [
      "Deshidratador Bio Origen con control de temperatura",
      "Cuchillo bien afilado o rebanadadora",
      "Recipiente para marinar",
      "Papel absorbente",
    ],
    steps: [
      "Retirar toda la grasa visible de la carne (la grasa se enrancia al deshidratar).",
      "Cortar tiras de 5 mm siguiendo la veta.",
      "Mezclar todos los ingredientes del marinado.",
      "Marinar la carne en refrigerador por 12-24 horas.",
      "Retirar del marinado y secar bien con papel absorbente.",
      "Distribuir en bandejas sin superponer.",
      "Deshidratar a 70°C por 6-8 horas, dando vuelta a las 3 horas.",
      "La carne está lista cuando se dobla sin quebrarse pero no tiene humedad.",
      "Guardar en bolsa sellada; consumir en 1 semana o refrigerar.",
    ],
    variations: [
      "Teriyaki: agregar jengibre rallado, sake y azúcar moreno al marinado",
      "Picante: duplicar el pimentón y agregar chile molido",
    ],
    uses: ["Snack proteico", "Camping y trekking", "Picadas gourmet"],
    image: "/recetas/beef-jerky.jpg",
    images: [],
    featured: true,
    season: null,
  },
  {
    name: "Hongos Gourmet Deshidratados",
    slug: "hongos-gourmet-deshidratados",
    emoji: "🍄",
    description:
      "Portobellos, shiitake y gírgolas deshidratados para intensificar su sabor umami. Se rehidratan en minutos.",
    category: "Avanzado",
    difficulty: "Difícil",
    time: "8-12 horas",
    temperature: "45°C",
    ingredients: ["300 g de portobellos", "200 g de shiitake", "200 g de gírgolas"],
    equipment: [
      "Deshidratador Bio Origen",
      "Pincel o trapo húmedo para limpiar",
      "Mallas finas para piezas pequeñas",
    ],
    steps: [
      "Limpiar los hongos con pincel o paño húmedo (no sumergir en agua).",
      "Cortar los portobellos en láminas de 5 mm.",
      "Dejar los shiitake y gírgolas pequeños enteros; cortar los grandes.",
      "Distribuir en bandejas sin superposición.",
      "Deshidratar a 45°C por 8-12 horas hasta que estén completamente rígidos.",
      "Dejar enfriar y guardar en frasco hermético lejos de la humedad.",
    ],
    variations: [
      "Condimentados con sal, tomillo y ajo antes de deshidratar",
      "Moler para obtener polvo de hongos para salsas y risottos",
    ],
    uses: [
      "Rehidratar en agua caliente para salsas",
      "Polvo umami para sopas",
      "Rellenos de pasta fresca",
    ],
    image: "/recetas/hongos-gourmet-deshidratados.jpg",
    images: [],
    featured: false,
    season: "Otoño",
  },
  {
    name: "Barritas Energéticas",
    slug: "barritas-energeticas",
    emoji: "🌾",
    description:
      "Barritas de avena, frutas deshidratadas y semillas comprimidas y secadas para una textura firme y duradera.",
    category: "Avanzado",
    difficulty: "Difícil",
    time: "8-10 horas",
    temperature: "57°C",
    ingredients: [
      "200 g de avena arrollada",
      "100 g de dátiles sin carozo",
      "50 g de almendras",
      "50 g de semillas de girasol",
      "30 g de chips de manzana deshidratada",
      "3 cucharadas de manteca de maní",
      "2 cucharadas de miel",
      "1 cucharadita de canela",
      "Pizca de sal",
    ],
    equipment: [
      "Procesadora",
      "Deshidratador Bio Origen",
      "Molde rectangular o papel film",
      "Lámina de silicona",
    ],
    steps: [
      "Procesar los dátiles hasta obtener una pasta.",
      "Mezclar pasta de dátiles con manteca de maní, miel, canela y sal.",
      "Incorporar avena, almendras picadas, semillas y frutas deshidratadas.",
      "Mezclar hasta que todo se integre.",
      "Extender sobre lámina de silicona con un grosor de 1.5-2 cm.",
      "Cortar en barritas antes de deshidratar.",
      "Deshidratar a 57°C por 8-10 horas hasta que estén firmes.",
      "Envolver individualmente en papel film.",
    ],
    variations: [
      "Con cacao en polvo y naranja confitada",
      "Con proteína en polvo para versión deportiva",
    ],
    uses: ["Snack pre-entrenamiento", "Desayuno portátil", "Trekking y viajes"],
    image: "/recetas/barritas-energeticas.jpg",
    images: [],
    featured: true,
    season: null,
  },
  {
    name: "Frutos Secos Activados",
    slug: "frutos-secos-activados",
    emoji: "🥜",
    description:
      "Almendras y nueces remojadas y luego secadas a baja temperatura: quedan más crocantes y digeribles que las crudas, sin tostar.",
    category: "Avanzado",
    difficulty: "Difícil",
    time: "12-24 horas + 8 hs de remojo",
    temperature: "45°C",
    ingredients: [
      "300 g de almendras crudas",
      "200 g de nueces peladas",
      "150 g de castañas de cajú crudas",
      "1 cucharada de sal marina",
      "Agua filtrada para el remojo",
    ],
    equipment: [
      "Deshidratador Bio Origen",
      "Bols grandes",
      "Colador",
      "Frascos herméticos",
    ],
    steps: [
      "Remojar cada fruto seco por separado en agua con sal: almendras 8-12 hs, nueces 6-8 hs, castañas 2-4 hs.",
      "Descartar el agua de remojo (arrastra los antinutrientes) y enjuagar muy bien.",
      "Escurrir al menos 20 minutos en colador.",
      "Distribuir en una sola capa en las bandejas del Deshidratador Bio Origen.",
      "Deshidratar a 45°C durante 12-24 horas según el fruto y la humedad ambiente.",
      "No superar los 45°C: por encima de esa temperatura se degradan los aceites y se enrancian antes.",
      "Verificar el punto partiendo uno al medio: debe estar seco y crocante hasta el centro.",
      "Enfriar por completo y guardar en frasco hermético; duran hasta 4 meses.",
    ],
    variations: [
      "Salados con especias: pimentón ahumado, ajo en polvo y romero",
      "Dulces: con canela y una pizca de azúcar mascabo antes de deshidratar",
    ],
    uses: ["Snack diario", "Leches vegetales", "Base de mantecas y quesos de frutos secos"],
    image: "/recetas/frutos-secos-activados.jpg",
    images: [],
    featured: false,
    season: null,
  },
  {
    name: "Masa Madre Deshidratada",
    slug: "masa-madre-deshidratada",
    emoji: "🍞",
    description:
      "Una forma de guardar tu masa madre por años sin alimentarla: se seca en escamas y se reactiva en 48 horas cuando la necesites.",
    category: "Avanzado",
    difficulty: "Difícil",
    time: "6-10 horas",
    temperature: "35°C",
    ingredients: [
      "150 g de masa madre activa, en su pico de fermentación",
      "Harina extra para el reactivado",
    ],
    equipment: [
      "Deshidratador Bio Origen con control fino de temperatura",
      "Lámina de silicona o papel manteca",
      "Espátula acodada",
      "Bolsa hermética o frasco con desecante",
    ],
    steps: [
      "Alimentar la masa madre y esperar a que duplique: se deshidrata en el pico de actividad.",
      "Extender una capa muy fina, de 1-2 mm, sobre la lámina de silicona.",
      "Deshidratar a 35°C durante 6-10 horas. No superar los 40°C: por encima mueren las levaduras.",
      "Está lista cuando la lámina se levanta sola y se quiebra como una galleta.",
      "Romper en escamas chicas con las manos limpias y bien secas.",
      "Guardar en bolsa hermética con una etiqueta que indique la fecha.",
      "Para reactivar: mezclar 20 g de escamas con 40 g de agua tibia, esperar 4 hs y alimentar con 40 g de harina cada 12 hs durante 2 días.",
    ],
    variations: [
      "Molida en polvo fino, ocupa menos lugar y se hidrata más rápido",
      "Envasada al vacío en porciones de 20 g para regalar o intercambiar",
    ],
    uses: [
      "Backup de tu fermento",
      "Llevar la masa madre de viaje",
      "Compartir el cultivo con otros panaderos",
    ],
    image: "/recetas/masa-madre-deshidratada.jpg",
    images: [],
    featured: false,
    season: null,
  },
  {
    name: "Charqui de Pollo",
    slug: "charqui-de-pollo",
    emoji: "🍗",
    description:
      "Pechuga de pollo marinada, precocida y deshidratada. Más magra que el charqui de vaca, con un paso de precocción obligatorio por seguridad alimentaria.",
    category: "Avanzado",
    difficulty: "Difícil",
    time: "5-7 horas + 8 hs de marinado",
    temperature: "70°C",
    ingredients: [
      "800 g de pechuga de pollo sin piel ni grasa",
      "60 ml de salsa de soja",
      "2 cucharadas de jugo de limón",
      "1 cucharadita de ajo en polvo",
      "1 cucharadita de jengibre rallado",
      "1 cucharadita de pimentón dulce",
      "½ cucharadita de pimienta negra",
    ],
    equipment: [
      "Deshidratador Bio Origen con control de temperatura",
      "Termómetro de punzón (imprescindible)",
      "Cuchillo bien afilado",
      "Olla o horno para la precocción",
      "Papel absorbente",
    ],
    steps: [
      "Llevar la pechuga 40 minutos al freezer: firme se corta mucho mejor.",
      "Cortar tiras de 5 mm en contra de la fibra, retirando cualquier resto de grasa o cartílago.",
      "Marinar en heladera durante 8-12 horas dentro de un recipiente tapado.",
      "Precocer las tiras en el marinado hirviendo durante 3-5 minutos, hasta alcanzar 74°C en el centro (verificar con termómetro). Este paso no es opcional: el pollo requiere precocción antes de deshidratar.",
      "Escurrir y secar muy bien con papel absorbente.",
      "Distribuir en las bandejas del Deshidratador Bio Origen sin superponer.",
      "Deshidratar a 70°C durante 5-7 horas, dando vuelta las tiras a las 3 horas.",
      "Está listo cuando la tira se dobla y se agrieta, pero no se parte del todo.",
      "Enfriar por completo, guardar en bolsa hermética y consumir dentro de las 2 semanas; para más tiempo, freezer.",
    ],
    variations: [
      "Versión BBQ: reemplazar la soja por salsa barbacoa y pimentón ahumado",
      "Versión picante: agregar ají molido y unas gotas de salsa picante al marinado",
    ],
    uses: ["Snack proteico bajo en grasa", "Post entrenamiento", "Trekking y viajes largos"],
    image: "/recetas/charqui-de-pollo.jpg",
    images: [],
    featured: false,
    season: null,
  },
];
